# Version 0.1
services:
  tensorflow-docker-jupyter:
    container_name: tensorflow-jupyter
    image: tensorflow/tensorflow:latest-gpu-jupyter
    ports:
      - "8888:8888"
    restart: unless-stopped
    volumes:
      - "./:/tf/workdir"
    command: 'jupyter notebook --notebook-dir=/tf/workdir --ip 0.0.0.0 --allow-root --NotebookApp.allow_origin=https://colab.research.google.com  --NotebookApp.port_retries=0' 
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']  
            capabilities: [gpu]
